import pandas as pd


def merge_candidates_info(all_candidates_data, elected_candidates_data):
    """Merge data of all and elected candidates

    Args:
        all_candidates_data (DataFrame): data of all candidates (generated by get_candidates_info function)
        elected_candidates_data (DataFrame): data of elected candidates (generated by get_candidates_info function)

    Returns:
        DataFrame: merged data of all and elected candidates
    """
    # merge data
    merged_data = pd.merge(
        all_candidates_data,
        elected_candidates_data,
        how="outer",
        on=["Рада", "Партія", "Прізвище, ім’я, по батькові"],
        suffixes=["", "_x"],
        indicator=True,
    )
    # clean the merged DataFrame
    # fill columns from elected candidates data which is not provided in all candidates data
    cols_to_fill = [
        "Регіон",
        "Тип ради",
        "ТВО/ОВО",
        "Відомості",
        "Кількість отриманих голосів",
        "% голосів від квоти",
    ]
    for col in cols_to_fill:
        merged_data[col].fillna(merged_data[col + "_x"], inplace=True)
    # add status column using merge indicator
    merged_data["Статус"] = merged_data.apply(
        lambda x: "не обрано" if x["_merge"] == "left_only" else "обрано", axis=1
    )
    # drop unnecessary columns
    cols_to_drop = [col + "_x" for col in cols_to_fill]
    cols_to_drop.append("_merge")
    merged_data.drop(columns=cols_to_drop, inplace=True)
    return merged_data
